// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(mongoose) {
    var ObjectId, Schema, lawyerSchema, models, sanSchema;
    Schema = mongoose.Schema;
    ObjectId = Schema.ObjectId;
    lawyerSchema = new Schema({
      firstName: String,
      middleName: String,
      lastName: String,
      called: String
    });
    sanSchema = new Schema({
      lawyer: ObjectId
    });
    models = {
      Lawyer: mongoose.model("Lawyer", lawyerSchema),
      San: mongoose.model("San", sanSchema)
    };
    return models;
  };

}).call(this);
