// Generated by CoffeeScript 1.9.2
(function() {
  var Sequelize, app, bodyParser, connectDb, express, logger, moment, path, sequelize;

  express = require("express");

  path = require("path");

  logger = require("morgan");

  bodyParser = require("body-parser");

  Sequelize = require("sequelize");

  moment = require("moment");

  sequelize = new Sequelize("nba-agc", "root", "", {
    port: 3306,
    host: 'localhost',
    logging: false
  });

  connectDb = function() {
    return sequelize.sync().complete(function(err) {
      if (!!err) {
        return console.log("Unable to connect to database");
      }
    });
  };

  connectDb();

  app = express();

  app.set('port', process.env.PORT || 3005);

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(express["static"](path.join(__dirname, 'public'), {
    maxAge: 86400000
  }));

  app.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

  app.use(logger('tiny'));

  app.get('/api', function(req, res) {
    return res.send({
      done: false
    });
  });

  app.post('/api/amountDue', function(req, res) {
    var atBar, theYear;
    theYear = parseInt(req.body.yearCalled);
    atBar = 2015 - theYear;
    return res.send({
      amount: 50000
    });
  });

  app.get('*', function(req, res) {
    return res.redirect(302, "/#" + req.originalUrl);
  });

  app.use(function(err, req, res) {
    console.error(err.stack);
    return res.send({
      message: err.message
    }, 500);
  });

}).call(this);
